### PR TITLE
seup.py fails because README.md not included in Fileseq tar.gz

### PR DESCRIPTION
**Pull request by GlenWalker**

### CODE REVIEW

**Comment by justinfx** [comment]
Thanks for this fix!

**Comment by GlenWalker** [comment]
Awesome, thanks for the quick turnaround. You don't feel like rolling a 1.6.1 to PyPI do you?

**Comment by justinfx** [comment]
Tagged and uploaded to PyPI: https://pypi.org/project/Fileseq/1.6.1/

**Comment by GlenWalker** [comment]
Thanks! Installed successfully.

**Pull request merged**
