### PR TITLE
Update with python3 support

### PR DESCRIPTION
**Pull request by justinfx**
refs #63  and #67 

This is another pass at an update to support both python 2 and 3. Based on work in #67, I decided to try a second pass at this using the "future" module, as it is something I plan to continue using in the conversion of the projects that I maintain. Many of the changes are similar, but instead of introducing `six` types all over the codebase, we instead use the `builtin` native-looking types from the `future` library.

### CODE REVIEW

**Comment by justinfx** [comment]
@donalm , if you get some free time can you have a look at this branch? I thought it would be good for perspective to do a py3 conversion on my own, using future, and compare it to what your #67 efforts are doing. Been thinking of how to go about releasing this, and I am really leaning towards making this a v2 release, and only doing v1 backport patches as needed. 
One thing I am wondering about is the future builtins backport types such as `str` being returned. They are meant to behave properly in py2 and py3, but I did notice that something like the `str.translate()` signature follows py3. So I was concerned about whether that matters for users. I've asked on the python-future mailing list. My impression of future is that it is really trying to make the code style conform to natural py3, and be a compatability aspect to py2.

**Comment by justinfx** [comment]
Anyone have a chance to give this a try? I don't yet have a pressing need to have a release of this at my own studio, so I am kind of holding out to see if there is any external feedback.

**Comment by donalm** [comment]
Hey sorry @justinfx I'm embarrassed that I haven't replied to this yet. I've been a bit busy with other stuff. Things should mellow out a bit over the next month and I'm looking forward to checking out this branch when they do.

**Comment by justinfx** [comment]
This has been sitting for long enough and I decided to just go with merging and releasing as 1.8.0. The expected behavior is to have the same py2 byte strings for existing users, so any breaking effects are to be considered a bug. The API remains the same.

**Pull request merged**
