### PR TITLE
#37 Adds/modifies files to support the Github-TravisCI integration.

### PR DESCRIPTION
**Pull request by matthewkapfhammer**
I pointed the build badge to sqlboy/fileseq in anticipation of @sqlboy or @justinfx handling the Travis setup there.

### CODE REVIEW

**Comment by justinfx** [comment]
@sqlboy , it looks like you would have to login with https://travis-ci.org and enable it for this repo. I thought it would display it for me since I am a maintainer, but it only shows my own personal namespace + any organizations.

**Comment by matthewkapfhammer** [comment]
@sqlboy, any chance you can take a look? :)

**Comment by justinfx** [comment]
@sqlboy , did you actually log into travis and enable this repo? Or did you only merge this pull request? I don't see that you have enabled travis yet.

**Comment by matthewkapfhammer** [comment]
Bump :D

**Pull request merged**
